name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -c "import app; print('App imports successfully')"
        
    - name: Build Docker image
      run: |
        docker build -t collatz-conjecture .
        
    - name: Test Docker image locally
      run: |
        docker run -d --name test-collatz -p 8001:8000 collatz-conjecture
        sleep 10
        curl -f http://localhost:8001/api/health || exit 1
        docker stop test-collatz
        docker rm test-collatz
        
    - name: Deploy to Oracle Cloud
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Deployment to Oracle Cloud would happen here"
        echo "You'll need to configure Oracle Cloud credentials and deployment steps"
        echo "This is a template - customize based on your Oracle Cloud setup"
